// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/auth.proto

package omo_msa_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 注册的请求
type SignupRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{0}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 注册的回复
type SignupResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{1}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignupResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 登录的请求
type SigninRequest struct {
	Strategy             Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=omo.msa.account.Strategy" json:"strategy,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninRequest) Reset()         { *m = SigninRequest{} }
func (m *SigninRequest) String() string { return proto.CompactTextString(m) }
func (*SigninRequest) ProtoMessage()    {}
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{2}
}

func (m *SigninRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninRequest.Unmarshal(m, b)
}
func (m *SigninRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninRequest.Marshal(b, m, deterministic)
}
func (m *SigninRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninRequest.Merge(m, src)
}
func (m *SigninRequest) XXX_Size() int {
	return xxx_messageInfo_SigninRequest.Size(m)
}
func (m *SigninRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SigninRequest proto.InternalMessageInfo

func (m *SigninRequest) GetStrategy() Strategy {
	if m != nil {
		return m.Strategy
	}
	return Strategy_STRATEGY_NONE
}

func (m *SigninRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SigninRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 登录的回复
type SigninResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninResponse) Reset()         { *m = SigninResponse{} }
func (m *SigninResponse) String() string { return proto.CompactTextString(m) }
func (*SigninResponse) ProtoMessage()    {}
func (*SigninResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{3}
}

func (m *SigninResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninResponse.Unmarshal(m, b)
}
func (m *SigninResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninResponse.Marshal(b, m, deterministic)
}
func (m *SigninResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninResponse.Merge(m, src)
}
func (m *SigninResponse) XXX_Size() int {
	return xxx_messageInfo_SigninResponse.Size(m)
}
func (m *SigninResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SigninResponse proto.InternalMessageInfo

func (m *SigninResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SigninResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SigninResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// 登出的请求
type SignoutRequest struct {
	Strategy             Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=omo.msa.account.Strategy" json:"strategy,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignoutRequest) Reset()         { *m = SignoutRequest{} }
func (m *SignoutRequest) String() string { return proto.CompactTextString(m) }
func (*SignoutRequest) ProtoMessage()    {}
func (*SignoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{4}
}

func (m *SignoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignoutRequest.Unmarshal(m, b)
}
func (m *SignoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignoutRequest.Marshal(b, m, deterministic)
}
func (m *SignoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignoutRequest.Merge(m, src)
}
func (m *SignoutRequest) XXX_Size() int {
	return xxx_messageInfo_SignoutRequest.Size(m)
}
func (m *SignoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignoutRequest proto.InternalMessageInfo

func (m *SignoutRequest) GetStrategy() Strategy {
	if m != nil {
		return m.Strategy
	}
	return Strategy_STRATEGY_NONE
}

func (m *SignoutRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// 登出的回复
type SignoutResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignoutResponse) Reset()         { *m = SignoutResponse{} }
func (m *SignoutResponse) String() string { return proto.CompactTextString(m) }
func (*SignoutResponse) ProtoMessage()    {}
func (*SignoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{5}
}

func (m *SignoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignoutResponse.Unmarshal(m, b)
}
func (m *SignoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignoutResponse.Marshal(b, m, deterministic)
}
func (m *SignoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignoutResponse.Merge(m, src)
}
func (m *SignoutResponse) XXX_Size() int {
	return xxx_messageInfo_SignoutResponse.Size(m)
}
func (m *SignoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignoutResponse proto.InternalMessageInfo

func (m *SignoutResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 重置密码的请求
type ResetPasswdRequest struct {
	Strategy             Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=omo.msa.account.Strategy" json:"strategy,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswdRequest) Reset()         { *m = ResetPasswdRequest{} }
func (m *ResetPasswdRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswdRequest) ProtoMessage()    {}
func (*ResetPasswdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{6}
}

func (m *ResetPasswdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswdRequest.Unmarshal(m, b)
}
func (m *ResetPasswdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswdRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswdRequest.Merge(m, src)
}
func (m *ResetPasswdRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswdRequest.Size(m)
}
func (m *ResetPasswdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswdRequest proto.InternalMessageInfo

func (m *ResetPasswdRequest) GetStrategy() Strategy {
	if m != nil {
		return m.Strategy
	}
	return Strategy_STRATEGY_NONE
}

func (m *ResetPasswdRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ResetPasswdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 重置密码的回复
type ResetPasswdResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswdResponse) Reset()         { *m = ResetPasswdResponse{} }
func (m *ResetPasswdResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswdResponse) ProtoMessage()    {}
func (*ResetPasswdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2028ec5cbc6bcd, []int{7}
}

func (m *ResetPasswdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswdResponse.Unmarshal(m, b)
}
func (m *ResetPasswdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswdResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswdResponse.Merge(m, src)
}
func (m *ResetPasswdResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswdResponse.Size(m)
}
func (m *ResetPasswdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswdResponse proto.InternalMessageInfo

func (m *ResetPasswdResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "omo.msa.account.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "omo.msa.account.SignupResponse")
	proto.RegisterType((*SigninRequest)(nil), "omo.msa.account.SigninRequest")
	proto.RegisterType((*SigninResponse)(nil), "omo.msa.account.SigninResponse")
	proto.RegisterType((*SignoutRequest)(nil), "omo.msa.account.SignoutRequest")
	proto.RegisterType((*SignoutResponse)(nil), "omo.msa.account.SignoutResponse")
	proto.RegisterType((*ResetPasswdRequest)(nil), "omo.msa.account.ResetPasswdRequest")
	proto.RegisterType((*ResetPasswdResponse)(nil), "omo.msa.account.ResetPasswdResponse")
}

func init() {
	proto.RegisterFile("proto/account/auth.proto", fileDescriptor_8a2028ec5cbc6bcd)
}

var fileDescriptor_8a2028ec5cbc6bcd = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0x6e, 0xf3, 0x56, 0x7d, 0xcb, 0x55, 0xb4, 0xd2, 0x31, 0x50, 0x32, 0x40, 0x65, 0x18, 0x98,
	0x52, 0xa9, 0x88, 0x1f, 0x00, 0x03, 0x0c, 0x48, 0x08, 0xa5, 0xb0, 0xb0, 0x99, 0xd4, 0x6a, 0x23,
	0x54, 0x3b, 0xe4, 0x6c, 0x55, 0x2c, 0xec, 0xfc, 0x37, 0x7e, 0x14, 0x6a, 0x9c, 0xa4, 0x1f, 0x69,
	0x32, 0x14, 0xd8, 0x62, 0xdf, 0xe3, 0xe7, 0xc3, 0x77, 0x31, 0xf4, 0xa2, 0x58, 0x69, 0x35, 0xe0,
	0x41, 0xa0, 0x8c, 0xd4, 0x03, 0x6e, 0xf4, 0xd4, 0x4b, 0xb6, 0xb0, 0xab, 0x66, 0xca, 0x9b, 0x11,
	0xf7, 0xd2, 0x9a, 0xeb, 0xae, 0x43, 0x69, 0xca, 0x63, 0x31, 0xb6, 0x60, 0x76, 0x0b, 0xfb, 0xa3,
	0x70, 0x22, 0x4d, 0xe4, 0x8b, 0x37, 0x23, 0x48, 0xa3, 0x0b, 0x2d, 0x43, 0x22, 0x96, 0x7c, 0x26,
	0x7a, 0xf5, 0x7e, 0xfd, 0x7c, 0xcf, 0xcf, 0xd7, 0x8b, 0x5a, 0xc4, 0x89, 0xe6, 0x2a, 0x1e, 0xf7,
	0x1c, 0x5b, 0xcb, 0xd6, 0xec, 0x09, 0x3a, 0x19, 0x11, 0x45, 0x4a, 0x92, 0xc0, 0x01, 0x34, 0x49,
	0x73, 0x6d, 0x28, 0xe1, 0x69, 0x0f, 0x0f, 0xbd, 0x0d, 0x63, 0xde, 0x28, 0x29, 0xfb, 0x29, 0x0c,
	0x11, 0x1a, 0xc6, 0x84, 0x19, 0x75, 0xf2, 0xcd, 0x3e, 0xac, 0xbf, 0x50, 0x66, 0xfe, 0x2e, 0xa1,
	0x45, 0x3a, 0xe6, 0x5a, 0x4c, 0xde, 0x13, 0xde, 0xce, 0xf0, 0x68, 0x0b, 0xaf, 0x05, 0xf8, 0x39,
	0x74, 0x2d, 0x96, 0x53, 0x11, 0xeb, 0xdf, 0x46, 0xac, 0xb9, 0x8d, 0xb5, 0xd0, 0xff, 0xc5, 0x58,
	0xd8, 0x87, 0x36, 0x0f, 0x02, 0x41, 0xf4, 0xa8, 0x5e, 0x85, 0x4c, 0x55, 0x57, 0xb7, 0x58, 0x68,
	0x85, 0x95, 0xd1, 0x3f, 0x4c, 0xbe, 0x21, 0xe5, 0x14, 0xa5, 0xae, 0xa1, 0x9b, 0x4b, 0xed, 0x18,
	0x92, 0x7d, 0xd6, 0x01, 0x7d, 0x41, 0x42, 0x3f, 0x2c, 0x6e, 0x6e, 0xfc, 0xd7, 0x9e, 0x2b, 0x7b,
	0x76, 0x03, 0x07, 0x6b, 0x56, 0x76, 0xcc, 0x34, 0xfc, 0x72, 0xa0, 0x71, 0x65, 0xf4, 0x14, 0xef,
	0xa0, 0x69, 0x67, 0x1b, 0x8f, 0x8b, 0x67, 0x56, 0xff, 0x1e, 0xf7, 0xa4, 0xb4, 0x6e, 0x4d, 0xb0,
	0x5a, 0x46, 0x16, 0xca, 0x12, 0xb2, 0x7c, 0xd4, 0x4b, 0xc8, 0x96, 0xa3, 0xc8, 0x6a, 0x78, 0x0f,
	0xff, 0xd3, 0xd6, 0xe1, 0x76, 0xf4, 0x72, 0x7e, 0xdc, 0x7e, 0x39, 0x20, 0xe7, 0x7b, 0x86, 0xf6,
	0xca, 0xd5, 0xe1, 0x69, 0xe1, 0x48, 0xb1, 0xc7, 0xee, 0x59, 0x35, 0x28, 0xe3, 0x7e, 0x69, 0x26,
	0x2f, 0xce, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x39, 0xfe, 0x90, 0xba, 0x04, 0x00,
	0x00,
}
