// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/notification.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 通知
type Notification struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_2701af0bff053f3b, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Notification) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Notification)(nil), "account.Notification")
}

func init() {
	proto.RegisterFile("proto/account/notification.proto", fileDescriptor_2701af0bff053f3b)
}

var fileDescriptor_2701af0bff053f3b = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0xcf, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb,
	0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x4b, 0x09, 0xb1, 0x43, 0xe5, 0x94, 0xfc, 0xb8,
	0x78, 0xfc, 0x90, 0xa4, 0x85, 0xc4, 0xb8, 0xd8, 0x12, 0x93, 0x41, 0x2c, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0x25, 0x23, 0x35, 0x31, 0x45, 0x82, 0x09, 0x2c,
	0x0a, 0x66, 0x83, 0xc4, 0x92, 0xf2, 0x53, 0x2a, 0x25, 0x98, 0x21, 0x62, 0x20, 0x76, 0x12, 0x1b,
	0xd8, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x91, 0x63, 0x9d, 0x83, 0x00, 0x00,
	0x00,
}
