// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/query.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询列表的请求
type QueryListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryListRequest) Reset()         { *m = QueryListRequest{} }
func (m *QueryListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListRequest) ProtoMessage()    {}
func (*QueryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_232e5080efc7cf31, []int{0}
}

func (m *QueryListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListRequest.Unmarshal(m, b)
}
func (m *QueryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListRequest.Marshal(b, m, deterministic)
}
func (m *QueryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRequest.Merge(m, src)
}
func (m *QueryListRequest) XXX_Size() int {
	return xxx_messageInfo_QueryListRequest.Size(m)
}
func (m *QueryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRequest proto.InternalMessageInfo

func (m *QueryListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 查询列表的回复
type QueryListResponse struct {
	Status               *Status          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Account              []*AccountEntity `protobuf:"bytes,3,rep,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryListResponse) Reset()         { *m = QueryListResponse{} }
func (m *QueryListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListResponse) ProtoMessage()    {}
func (*QueryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_232e5080efc7cf31, []int{1}
}

func (m *QueryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListResponse.Unmarshal(m, b)
}
func (m *QueryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListResponse.Marshal(b, m, deterministic)
}
func (m *QueryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListResponse.Merge(m, src)
}
func (m *QueryListResponse) XXX_Size() int {
	return xxx_messageInfo_QueryListResponse.Size(m)
}
func (m *QueryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListResponse proto.InternalMessageInfo

func (m *QueryListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryListResponse) GetAccount() []*AccountEntity {
	if m != nil {
		return m.Account
	}
	return nil
}

// 查询个体的请求
type QuerySingleRequest struct {
	Field                QueryField `protobuf:"varint,1,opt,name=field,proto3,enum=account.QueryField" json:"field,omitempty"`
	Value                string     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QuerySingleRequest) Reset()         { *m = QuerySingleRequest{} }
func (m *QuerySingleRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySingleRequest) ProtoMessage()    {}
func (*QuerySingleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_232e5080efc7cf31, []int{2}
}

func (m *QuerySingleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySingleRequest.Unmarshal(m, b)
}
func (m *QuerySingleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySingleRequest.Marshal(b, m, deterministic)
}
func (m *QuerySingleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySingleRequest.Merge(m, src)
}
func (m *QuerySingleRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySingleRequest.Size(m)
}
func (m *QuerySingleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySingleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySingleRequest proto.InternalMessageInfo

func (m *QuerySingleRequest) GetField() QueryField {
	if m != nil {
		return m.Field
	}
	return QueryField_QUERY_FIELD_NONE
}

func (m *QuerySingleRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// 查询列表的回复
type QuerySingleResponse struct {
	Status               *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Account              *AccountEntity `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QuerySingleResponse) Reset()         { *m = QuerySingleResponse{} }
func (m *QuerySingleResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySingleResponse) ProtoMessage()    {}
func (*QuerySingleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_232e5080efc7cf31, []int{3}
}

func (m *QuerySingleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySingleResponse.Unmarshal(m, b)
}
func (m *QuerySingleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySingleResponse.Marshal(b, m, deterministic)
}
func (m *QuerySingleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySingleResponse.Merge(m, src)
}
func (m *QuerySingleResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySingleResponse.Size(m)
}
func (m *QuerySingleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySingleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySingleResponse proto.InternalMessageInfo

func (m *QuerySingleResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QuerySingleResponse) GetAccount() *AccountEntity {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryListRequest)(nil), "account.QueryListRequest")
	proto.RegisterType((*QueryListResponse)(nil), "account.QueryListResponse")
	proto.RegisterType((*QuerySingleRequest)(nil), "account.QuerySingleRequest")
	proto.RegisterType((*QuerySingleResponse)(nil), "account.QuerySingleResponse")
}

func init() {
	proto.RegisterFile("proto/account/query.proto", fileDescriptor_232e5080efc7cf31)
}

var fileDescriptor_232e5080efc7cf31 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0xa5, 0x08, 0xc6, 0x69, 0xe2, 0x9f, 0xa9, 0x69, 0x28, 0x7a, 0x68, 0xb8, 0x58, 0x2f,
	0xd4, 0xe0, 0x03, 0xa8, 0x87, 0x7a, 0xf2, 0xe2, 0x36, 0x3e, 0x00, 0xb6, 0x8b, 0x92, 0x10, 0x96,
	0xb2, 0x83, 0x49, 0xef, 0xde, 0x7d, 0x65, 0xc3, 0x2c, 0x34, 0x90, 0x34, 0x31, 0x3d, 0x91, 0x99,
	0xf9, 0xf6, 0xdb, 0xdf, 0x37, 0x2c, 0x4c, 0x8a, 0x52, 0x91, 0x9a, 0xc7, 0xab, 0x95, 0xaa, 0x72,
	0x9a, 0x6f, 0x2a, 0x59, 0x6e, 0x43, 0xee, 0xe1, 0x49, 0xd3, 0xf4, 0xfd, 0xbe, 0x46, 0x7f, 0xc5,
	0xa5, 0x5c, 0x1b, 0x51, 0xf0, 0x04, 0x17, 0x6f, 0xf5, 0x99, 0xd7, 0x54, 0x93, 0x90, 0x9b, 0x4a,
	0x6a, 0xc2, 0x31, 0xb8, 0x2a, 0x49, 0xb4, 0x24, 0xcf, 0x9a, 0x5a, 0x33, 0x5b, 0x34, 0x15, 0x5e,
	0x81, 0xc3, 0x0e, 0xde, 0x80, 0xdb, 0xa6, 0x08, 0x7e, 0x2c, 0xb8, 0xec, 0x58, 0xe8, 0x42, 0xe5,
	0x5a, 0xe2, 0x2d, 0xb8, 0x9a, 0x62, 0xaa, 0x34, 0x7b, 0x0c, 0xa3, 0xf3, 0xb0, 0xb9, 0x3e, 0x5c,
	0x72, 0x5b, 0x34, 0xe3, 0xda, 0x94, 0x14, 0xc5, 0x59, 0x6b, 0xca, 0x05, 0xde, 0x43, 0x4b, 0xef,
	0xd9, 0x53, 0x7b, 0x36, 0x8c, 0xc6, 0xbb, 0xf3, 0xcf, 0xe6, 0xbb, 0xc8, 0x29, 0xa5, 0xad, 0x68,
	0x65, 0xc1, 0x3b, 0x20, 0x53, 0x2c, 0xd3, 0xfc, 0x33, 0x93, 0x6d, 0x94, 0x3b, 0x70, 0x92, 0x54,
	0x66, 0x6b, 0xa6, 0x38, 0x8b, 0x46, 0x3b, 0x17, 0xd6, 0xbe, 0xd4, 0x23, 0x61, 0x14, 0x35, 0xc8,
	0x77, 0x9c, 0x55, 0x92, 0x41, 0x4e, 0x85, 0x29, 0x82, 0x02, 0x46, 0x3d, 0xdb, 0x43, 0xe3, 0x75,
	0x82, 0x0c, 0x58, 0xf9, 0x5f, 0x90, 0xe8, 0xd7, 0x02, 0x87, 0xaf, 0xc4, 0x47, 0x38, 0xae, 0x77,
	0x8a, 0x93, 0x3e, 0x75, 0xe7, 0x57, 0xf9, 0xfe, 0xbe, 0x91, 0x61, 0x0c, 0x8e, 0x70, 0x01, 0xae,
	0xe1, 0xc6, 0xeb, 0xbe, 0xae, 0xb7, 0x24, 0xff, 0x66, 0xff, 0xb0, 0xb5, 0xf9, 0x70, 0xf9, 0xa9,
	0x3c, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa9, 0x24, 0x62, 0x6c, 0x02, 0x00, 0x00,
}
