// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.15.7
// source: proto/account/shared.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 策略
type Strategy int32

const (
	Strategy_STRATEGY_NONE Strategy = 0 // 无
	Strategy_STRATEGY_JWT  Strategy = 1 // JWT
)

// Enum value maps for Strategy.
var (
	Strategy_name = map[int32]string{
		0: "STRATEGY_NONE",
		1: "STRATEGY_JWT",
	}
	Strategy_value = map[string]int32{
		"STRATEGY_NONE": 0,
		"STRATEGY_JWT":  1,
	}
)

func (x Strategy) Enum() *Strategy {
	p := new(Strategy)
	*p = x
	return p
}

func (x Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_shared_proto_enumTypes[0].Descriptor()
}

func (Strategy) Type() protoreflect.EnumType {
	return &file_proto_account_shared_proto_enumTypes[0]
}

func (x Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strategy.Descriptor instead.
func (Strategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_shared_proto_rawDescGZIP(), []int{0}
}

// 查询字段
type QueryField int32

const (
	QueryField_QUERY_FIELD_NONE     QueryField = 0 //无
	QueryField_QUERY_FIELD_UUID     QueryField = 1 // UUID
	QueryField_QUERY_FIELD_USERNAME QueryField = 2 // Username
)

// Enum value maps for QueryField.
var (
	QueryField_name = map[int32]string{
		0: "QUERY_FIELD_NONE",
		1: "QUERY_FIELD_UUID",
		2: "QUERY_FIELD_USERNAME",
	}
	QueryField_value = map[string]int32{
		"QUERY_FIELD_NONE":     0,
		"QUERY_FIELD_UUID":     1,
		"QUERY_FIELD_USERNAME": 2,
	}
)

func (x QueryField) Enum() *QueryField {
	p := new(QueryField)
	*p = x
	return p
}

func (x QueryField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryField) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_shared_proto_enumTypes[1].Descriptor()
}

func (QueryField) Type() protoreflect.EnumType {
	return &file_proto_account_shared_proto_enumTypes[1]
}

func (x QueryField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryField.Descriptor instead.
func (QueryField) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_shared_proto_rawDescGZIP(), []int{1}
}

// 状态
type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 状态信息
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_account_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 账号实体
type AccountEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`    // 用户名
	Uuid      string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`            // 唯一识别标识
	Profile   string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`      // 个人资料
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 创建时间
	UpdatedAt int64  `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` // 修改时间
}

func (x *AccountEntity) Reset() {
	*x = AccountEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEntity) ProtoMessage() {}

func (x *AccountEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEntity.ProtoReflect.Descriptor instead.
func (*AccountEntity) Descriptor() ([]byte, []int) {
	return file_proto_account_shared_proto_rawDescGZIP(), []int{1}
}

func (x *AccountEntity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountEntity) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AccountEntity) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *AccountEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AccountEntity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_account_shared_proto protoreflect.FileDescriptor

var file_proto_account_shared_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x2f, 0x0a, 0x08,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x52, 0x41,
	0x54, 0x45, 0x47, 0x59, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59, 0x5f, 0x4a, 0x57, 0x54, 0x10, 0x01, 0x2a, 0x52, 0x0a,
	0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x51,
	0x55, 0x45, 0x52, 0x59, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44,
	0x5f, 0x55, 0x55, 0x49, 0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x51, 0x55, 0x45, 0x52, 0x59,
	0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41, 0x4d, 0x45, 0x10,
	0x02, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x3b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_account_shared_proto_rawDescOnce sync.Once
	file_proto_account_shared_proto_rawDescData = file_proto_account_shared_proto_rawDesc
)

func file_proto_account_shared_proto_rawDescGZIP() []byte {
	file_proto_account_shared_proto_rawDescOnce.Do(func() {
		file_proto_account_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_account_shared_proto_rawDescData)
	})
	return file_proto_account_shared_proto_rawDescData
}

var file_proto_account_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_account_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_account_shared_proto_goTypes = []interface{}{
	(Strategy)(0),         // 0: Strategy
	(QueryField)(0),       // 1: QueryField
	(*Status)(nil),        // 2: Status
	(*AccountEntity)(nil), // 3: AccountEntity
}
var file_proto_account_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_account_shared_proto_init() }
func file_proto_account_shared_proto_init() {
	if File_proto_account_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_account_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_account_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_account_shared_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_account_shared_proto_goTypes,
		DependencyIndexes: file_proto_account_shared_proto_depIdxs,
		EnumInfos:         file_proto_account_shared_proto_enumTypes,
		MessageInfos:      file_proto_account_shared_proto_msgTypes,
	}.Build()
	File_proto_account_shared_proto = out.File
	file_proto_account_shared_proto_rawDesc = nil
	file_proto_account_shared_proto_goTypes = nil
	file_proto_account_shared_proto_depIdxs = nil
}
