// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/shared.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 策略
type Strategy int32

const (
	Strategy_NONE Strategy = 0
	Strategy_JWT  Strategy = 1
)

var Strategy_name = map[int32]string{
	0: "NONE",
	1: "JWT",
}

var Strategy_value = map[string]int32{
	"NONE": 0,
	"JWT":  1,
}

func (x Strategy) String() string {
	return proto.EnumName(Strategy_name, int32(x))
}

func (Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{0}
}

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 账号实体
type AccountEntity struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Profile              string   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountEntity) Reset()         { *m = AccountEntity{} }
func (m *AccountEntity) String() string { return proto.CompactTextString(m) }
func (*AccountEntity) ProtoMessage()    {}
func (*AccountEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{1}
}

func (m *AccountEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountEntity.Unmarshal(m, b)
}
func (m *AccountEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountEntity.Marshal(b, m, deterministic)
}
func (m *AccountEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountEntity.Merge(m, src)
}
func (m *AccountEntity) XXX_Size() int {
	return xxx_messageInfo_AccountEntity.Size(m)
}
func (m *AccountEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AccountEntity proto.InternalMessageInfo

func (m *AccountEntity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AccountEntity) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *AccountEntity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccountEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("account.Strategy", Strategy_name, Strategy_value)
	proto.RegisterType((*Status)(nil), "account.Status")
	proto.RegisterType((*AccountEntity)(nil), "account.AccountEntity")
}

func init() {
	proto.RegisterFile("proto/account/shared.proto", fileDescriptor_49158a9607562c1b)
}

var fileDescriptor_49158a9607562c1b = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x46, 0xab, 0xda, 0x89, 0xed, 0x83, 0x42, 0xb8, 0x49, 0x84, 0x16, 0x4c, 0x26, 0xd3, 0xa1,
	0x19, 0x0a, 0xdd, 0x33, 0x64, 0xe9, 0x90, 0x82, 0x53, 0xe8, 0xac, 0x5a, 0xd7, 0xd4, 0xd0, 0x58,
	0x46, 0x3a, 0x0d, 0xf9, 0x21, 0xfd, 0xbf, 0xc5, 0x92, 0xea, 0x6c, 0xf7, 0xbd, 0x07, 0x0f, 0x0e,
	0xd6, 0xa3, 0x35, 0x6c, 0xb6, 0xaa, 0xeb, 0x8c, 0x1f, 0x78, 0xeb, 0xbe, 0x95, 0x25, 0xfd, 0x14,
	0x20, 0x16, 0x89, 0x6e, 0x5e, 0x60, 0x79, 0x64, 0xc5, 0xde, 0x21, 0x42, 0xde, 0x19, 0x4d, 0x52,
	0xd4, 0xa2, 0x59, 0xb4, 0xe1, 0x46, 0x09, 0xc5, 0x99, 0x9c, 0x53, 0x27, 0x92, 0xb7, 0xb5, 0x68,
	0xaa, 0xf6, 0x7f, 0x6e, 0x7e, 0x05, 0xdc, 0xed, 0x62, 0x63, 0x3f, 0x70, 0xcf, 0x17, 0x5c, 0x43,
	0xe9, 0x1d, 0xd9, 0x41, 0x9d, 0x63, 0xa3, 0x6a, 0xe7, 0x3d, 0xb5, 0xbd, 0xef, 0x75, 0x8a, 0x84,
	0x7b, 0x6a, 0x8f, 0xd6, 0x7c, 0xf5, 0x3f, 0x24, 0xb3, 0xd8, 0x4e, 0x13, 0xef, 0xa1, 0xea, 0x2c,
	0x29, 0x26, 0xbd, 0x63, 0x99, 0xd7, 0xa2, 0xc9, 0xda, 0x2b, 0x98, 0xac, 0x1f, 0x75, 0xb2, 0x8b,
	0x68, 0x67, 0xf0, 0xf8, 0x00, 0xe5, 0x91, 0xad, 0x62, 0x3a, 0x5d, 0xb0, 0x84, 0xfc, 0xf0, 0x76,
	0xd8, 0xaf, 0x6e, 0xb0, 0x80, 0xec, 0xf5, 0xe3, 0x7d, 0x25, 0x3e, 0x97, 0xe1, 0xfd, 0xe7, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x3d, 0xa9, 0xd6, 0x1c, 0x01, 0x00, 0x00,
}
