// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/shared.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 策略
type Strategy int32

const (
	Strategy_NONE Strategy = 0
	Strategy_JWT  Strategy = 1
)

var Strategy_name = map[int32]string{
	0: "NONE",
	1: "JWT",
}

var Strategy_value = map[string]int32{
	"NONE": 0,
	"JWT":  1,
}

func (x Strategy) String() string {
	return proto.EnumName(Strategy_name, int32(x))
}

func (Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{0}
}

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 账号
type Account struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Profile              string   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_49158a9607562c1b, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Account) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Account) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterEnum("account.Strategy", Strategy_name, Strategy_value)
	proto.RegisterType((*Status)(nil), "account.Status")
	proto.RegisterType((*Account)(nil), "account.Account")
}

func init() {
	proto.RegisterFile("proto/account/shared.proto", fileDescriptor_49158a9607562c1b)
}

var fileDescriptor_49158a9607562c1b = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x4d, 0xeb, 0xe4, 0xa6, 0xea, 0x26, 0xab, 0x02, 0xa9, 0xea, 0x54, 0x31, 0xd0,
	0x01, 0x89, 0xbd, 0x03, 0x0b, 0x43, 0x91, 0x52, 0x24, 0x66, 0x63, 0x1f, 0x25, 0x12, 0x89, 0x23,
	0xfb, 0x3c, 0xf0, 0x2b, 0xf8, 0xcb, 0x28, 0xb6, 0x09, 0xdb, 0xbd, 0xf7, 0xe9, 0x7d, 0xd2, 0xc1,
	0x66, 0xf4, 0x8e, 0xdd, 0x41, 0x1b, 0xe3, 0xe2, 0xc0, 0x87, 0xf0, 0xa9, 0x3d, 0xd9, 0xfb, 0x54,
	0xa2, 0x2c, 0xed, 0xee, 0x11, 0x56, 0x67, 0xd6, 0x1c, 0x03, 0x22, 0x54, 0xc6, 0x59, 0x52, 0x62,
	0x2b, 0xf6, 0xcb, 0x36, 0xdd, 0xa8, 0x40, 0xf6, 0x14, 0x82, 0xbe, 0x90, 0xba, 0xde, 0x8a, 0x7d,
	0xd3, 0xfe, 0xc5, 0xdd, 0x8f, 0x00, 0x79, 0xcc, 0x0e, 0xdc, 0x40, 0x1d, 0x03, 0xf9, 0x41, 0xf7,
	0x79, 0xdd, 0xb4, 0x73, 0x9e, 0xac, 0x31, 0x76, 0xb6, 0xcc, 0xd3, 0x3d, 0x59, 0x47, 0xef, 0x3e,
	0xba, 0x2f, 0x52, 0x8b, 0x6c, 0x2d, 0x11, 0x6f, 0xa0, 0x31, 0x9e, 0x34, 0x93, 0x3d, 0xb2, 0xaa,
	0x12, 0xfb, 0x2f, 0x26, 0x1a, 0x47, 0x5b, 0xe8, 0x32, 0xd3, 0xb9, 0xb8, 0xbb, 0x85, 0xfa, 0xcc,
	0x5e, 0x33, 0x5d, 0xbe, 0xb1, 0x86, 0xea, 0xf4, 0x72, 0x7a, 0x5a, 0x5f, 0xa1, 0x84, 0xc5, 0xf3,
	0xdb, 0xeb, 0x5a, 0xbc, 0xaf, 0xd2, 0xe3, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x40,
	0xee, 0x52, 0x16, 0x01, 0x00, 0x00,
}
